version: "3.1"

services:
  database:
    container_name: database
    image: postgres:14.5
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=project
    ports:
      - 5432:5432
    networks:
      - app
  web:
    container_name: web
    image: nginx:stable
    volumes:
      - ./api:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - app
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.laravel
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
      - ./conf/horizon.conf:/etc/supervisor/conf.d/horizon.conf
      - ./conf/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    depends_on:
      - database
      - redis
      - elasticsearch
    networks:
      - app
  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - 6379:6379
    networks:
      - app
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=secret
    mem_limit: 2g
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    networks:
      - app

networks:
  app:
