version: "3.1"

services:
  db:
    container_name: db
    image: postgres:14.5
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=project
    ports:
      - 5432:5432
    networks:
      - app
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.laravel
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    depends_on:
     - db
     - redis
    networks:
      - app
  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - 6379:6379
    networks:
      - app

networks:
  app:
